### ISSUE TITLE
Offline Mode : NullPointerException or UnknownHostException

### ISSUE THREAD

**Issue by lilianchiassai** [intirix/cloudpasswordmanager#16]
Cloud Password Manager throw different exceptions when I try ot log in and cannot reach the Nextcloud instance. I have  Offline Support enabled.

### Error 1
While not being connected to Internet and trying to access my passwords I get
"Failed: java.net.UnkownHostException: Unable to resolve host "hostname.com": No address associated with hostname.

### Error 2
While being connected to Internet and trying to access a down Nextcloud instance, I get
"Error: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Collection java.util.Map.values()' on a null object reference"

Having Offline Support enabled, both scenario should open the cached list of passwords.

**Comment by intirix** [comment]
I have published a new version (2.1.2) to the Alpha channel of the Play Store.  I hope this will fix the issue.

**Comment by lilianchiassai** [comment]
Thanks! I will let you know how it goes as soon as it is available to me.

**Comment by Gardakant** [comment]
Just installed and tested the alpha version. It still throws an exception when I'm offline and try to connect to nextcloud but right after it displays the login/passwords :)
Except the "cosmetic" point of view (it still throws an exception) it works for me, thanx.

**Comment by intirix** [comment]
I wanted to get something out there, so I left the Exception there.  I still want the user to know that something is wrong.  I think in the future, I will put a message on the password list page to indicate that the user is in offline mode.  I have promoted the Alpha release to Production.  Thanks for testing that out.
